// ─── Insta Analyzer · utils/csv.js ───────────────────────────────────────────
const CSVExporter = {

  // ── Single mode (followers OR following) ────────────────────────────────────
  build(data) {
    const { profile, mode, captured_at, count, users } = data;
    const date = captured_at ? captured_at.split('T')[0] : todayDate();
    const meta = [
      `# Profile: ${profile}`,
      `# Mode: ${capitalize(mode)}`,
      `# Captured: ${count}`,
      `# Date: ${date}`,
      `# Generated by: Insta Analyzer`,
      ``
    ];
    const header = `username,display_name,profile_url`;
    const rows   = Object.values(users).map(u =>
      `${this._e(u.username)},${this._e(u.display_name)},${this._e(u.profile_url)}`
    );
    return [...meta, header, ...rows].join('\n');
  },

  download(csv, profile, mode) {
    this._dl(csv, `insta_${mode}_${sanitizeFilename(profile)}_${todayDate()}.csv`, 'text/csv');
  },

  // ── Combined (both followers + following in one file) ───────────────────────
  buildCombined(profile, profileData) {
    const followers = profileData.followers || { users: {}, count: 0, captured_at: '' };
    const following = profileData.following || { users: {}, count: 0, captured_at: '' };
    const date      = todayDate();

    const lines = [
      `# Insta Analyzer — Combined Export`,
      `# Profile : ${profile}`,
      `# Date    : ${date}`,
      `# Followers: ${followers.count}  |  Following: ${following.count}`,
      ``,
      `## FOLLOWERS (${followers.count})`,
      `username,display_name,profile_url`,
      ...Object.values(followers.users).map(u =>
        `${this._e(u.username)},${this._e(u.display_name)},${this._e(u.profile_url)}`
      ),
      ``,
      `## FOLLOWING (${following.count})`,
      `username,display_name,profile_url`,
      ...Object.values(following.users).map(u =>
        `${this._e(u.username)},${this._e(u.display_name)},${this._e(u.profile_url)}`
      )
    ];
    return lines.join('\n');
  },

  downloadCombined(csv, profile) {
    this._dl(csv, `insta_combined_${sanitizeFilename(profile)}_${todayDate()}.csv`, 'text/csv');
  },

  // ── Comparison result ────────────────────────────────────────────────────────
  buildResult(profile, result) {
    const { notFollowingBack, notFollowedBack, mutual } = result;
    const date = todayDate();

    const section = (title, users) => [
      ``,
      `## ${title} (${users.length})`,
      `username,display_name,profile_url`,
      ...users.map(u =>
        `${this._e(u.username)},${this._e(u.display_name)},${this._e(u.profile_url)}`
      )
    ];

    const lines = [
      `# Insta Analyzer — Comparison Result`,
      `# Profile            : ${profile}`,
      `# Date               : ${date}`,
      `# Not Following Back : ${notFollowingBack.length}`,
      `# You Don't Follow   : ${notFollowedBack.length}`,
      `# Mutual             : ${mutual.length}`,
      ...section('NOT FOLLOWING YOU BACK', notFollowingBack),
      ...section('YOU DO NOT FOLLOW BACK', notFollowedBack),
      ...section('MUTUAL FOLLOWERS', mutual)
    ];
    return lines.join('\n');
  },

  downloadResult(csv, profile) {
    this._dl(csv, `insta_result_${sanitizeFilename(profile)}_${todayDate()}.csv`, 'text/csv');
  },

  // ── Internal ─────────────────────────────────────────────────────────────────
  _dl(content, filename, mime) {
    const blob = new Blob([content], { type: `${mime};charset=utf-8;` });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = filename; a.click();
    URL.revokeObjectURL(url);
  },

  _e(val) {
    if (!val) return '';
    const s = String(val);
    return (s.includes(',') || s.includes('"') || s.includes('\n'))
      ? `"${s.replace(/"/g, '""')}"` : s;
  }
};

function capitalize(s) { return s ? s.charAt(0).toUpperCase() + s.slice(1) : ''; }
