// ─── Insta Analyzer · utils/csv.js ───────────────────────────────────────────
// CSV export formatter with metadata header.

const CSVExporter = {

  /**
   * Build a CSV string from captured user data.
   * @param {object} data - { profile, mode, captured_at, count, users: {} }
   * @returns {string}
   */
  build(data) {
    const { profile, mode, captured_at, count, users } = data;
    const date = captured_at ? captured_at.split('T')[0] : todayDate();

    const metaLines = [
      `# Profile: ${profile}`,
      `# Mode: ${mode.charAt(0).toUpperCase() + mode.slice(1)}`,
      `# Captured: ${count}`,
      `# Date: ${date}`,
      `# Generated by: Insta Analyzer`,
      ``
    ];

    const header = `username,display_name,profile_url`;
    const rows = Object.values(users).map(u => {
      const uname = this._escape(u.username);
      const dname = this._escape(u.display_name);
      const url   = this._escape(u.profile_url);
      return `${uname},${dname},${url}`;
    });

    return [...metaLines, header, ...rows].join('\n');
  },

  /**
   * Trigger a CSV file download in the browser.
   * @param {string} csvString
   * @param {string} profile
   * @param {string} mode
   */
  download(csvString, profile, mode) {
    const filename = `insta_${mode}_${sanitizeFilename(profile)}_${todayDate()}.csv`;
    const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  },

  /** Escape a value for CSV (wrap in quotes if contains comma/quote/newline). */
  _escape(val) {
    if (!val) return '';
    const str = String(val);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  }
};
